[build]
  publish = "dist"

[functions]
  directory = "src/lambda"

[[redirects]]
  from = "/flickr"
  to = "/.netlify/functions/flickr"
  force = true

[[redirects]]
  from = "/content"
  to = "/.netlify/functions/data"
  force = true